const confirmCardConfig = {
    login: {
      title: "กรุณาเข้าสู่ระบบ?",
      confirmText: "เข้าสู่ระบบ",
      cancelText: "ยกเลิก",
      description: "กรุณาเข้าสู่ระบบเพื่อดำเนินการต่อ",
      confirmedTitle: "เรียบร้อย",
      confirmedDescription: "",
    },
    logout: {
      title: "ออกจากระบบ?",
      confirmText: "ออกจากระบบ",
      cancelText: "ยกเลิก",
      description: "",
      confirmedTitle: "เรียบร้อย",
      confirmedDescription: "",
    },
    createClub: {
      title: "ยืนยันการส่งคำขอ?",
      confirmText: "ส่งคำขอ",
      cancelText: "ตรวจเช็คอีกครั้ง",
      description: "กรุณาตรวจเช็คข้อมูลให้ครบถ้วนก่อนยืนยัน",
      confirmedTitle: "ส่งคำขอเรียบร้อย",
      confirmedDescription: "รอการตอบกลับทางอีเมลได้เลย!",
    },
    event: {
      title: "ยืนยันการสร้าง",
      confirmText: "ยืนยัน",
      cancelText: "ยกเลิก",
      description: "กรุณาตรวจเช็คข้อมูลให้ครบถ้วนก่อนยืนยัน",
      confirmedTitle: "เรียบร้อย",
      confirmedDescription: "",
    },
    profile: {
      title: "ยืนยันการเปลี่ยน?",
      confirmText: "ยืนยัน",
      cancelText: "ยกเลิก",
      description: "กรุณาตรวจเช็คข้อมูลให้ครบถ้วนก่อนยืนยัน",
      confirmedTitle: "ตั้งค่าเรียบร้อย",
      confirmedDescription: "",
    },
    errorUpload: {
      title: "กรุณาใช้ไฟล์รูปภาพเท่านั้น!",
      confirmText: "",
      cancelText: "ตกลง",
      description: "",
      confirmedTitle: "",
      confirmedDescription: "",
    },
    errorEmail: {
      title: "Error!",
      confirmText: "",
      cancelText: "ตกลง",
      description: "",
      confirmedTitle: "",
      confirmedDescription: "",  
    },
    errorEmail: {
      title: "อีเมลไม่ถูกต้อง",
      confirmText: "",
      cancelText: "ตกลง",
      description: "โปรดระบุอีเมลให้ถูกต้อง",
      confirmedTitle: "",
      confirmedDescription: "",  
    },
    errorEmpty: {
      title: "Error Empty field",
      confirmText: "",
      cancelText: "ตกลง",
      description: "โปรดกรอกส่วนที่ยังว่างอยู่ให้ครบถ้วน",
      confirmedTitle: "",
      confirmedDescription: "",  
    },
    errorURL: {
      title: "URL ไม่ถูกต้อง",
      confirmText: "",
      cancelText: "ตกลง",
      description: "โปรดระบุลิงค์หรือ URL ให้ถูกต้อง",
      confirmedTitle: "",
      confirmedDescription: "",  
    },
    error: {
        title: "Error!",
        confirmText: "",
        cancelText: "ตกลง",
        description: "",
        confirmedTitle: "",
        confirmedDescription: "",  
    },
    applyRegistration: {
        title: "ยืนยันการเปิดรับสมัคร",
        confirmText: "ตกลง",
        cancelText: "ยกเลิก",
        description: "กรุณาตรวจเช็คข้อมูลให้ครบถ้วนก่อนยืนยัน",
        confirmedTitle: "เปิดรับสมัครเรียบร้อย!",
        confirmedDescription: "",  
    },
    eventApprove: {
        title: "ยืนยันการส่งคำขอ?",
        confirmText: "ส่งคำขอ",
        cancelText: "ตรวจเช็คอีกครั้ง",
        description: "กรุณาตรวจเช็คข้อมูลให้ครบถ้วนก่อนยืนยัน",
        confirmedTitle: "ส่งคำขอเรียบร้อย",
        confirmedDescription: "รอการตอบกลับทางอีเมลได้เลย!",
      },
    registrationConfirm: {
      title: "ยืนยันการสมัคร",
      confirmText: "ตกลง",
      cancelText: "ยกเลิก",
      description: "กรุณาตรวจเช็คข้อมูลให้ครบถ้วนก่อนยืนยัน",
      confirmedTitle: "ส่งคำขอเรียบร้อย",
      confirmedDescription: "รอการตอบกลับทางอีเมลได้เลย!",
    },
    alreadyInClub: {
      title: "คุณอยู่ชมรมนี้แล้ว",
      confirmText: "",
      cancelText: "ตกลง",
      description: "คุณไม่สามารถสมัครชมรมที่คุณมีรายชื่อยู่แล้วได้",
      confirmedTitle: "",
      confirmedDescription: "",
    },
    alreadyApplied: {
      title: "คุณได้สมัครเรียบร้อยแล้ว",
      confirmText: "",
      cancelText: "ตกลง",
      description: "ชมรมสามารถสมัครเข้าชมรม ได้เพียงรอบเดียวเท่านั้น",
      confirmedTitle: "",
      confirmedDescription: "",
    },
    adminProhibit: {
      title: "คุณเป็นแอดมิน",
      confirmText: "",
      cancelText: "ตกลง",
      description: "",
      confirmedTitle: "",
      confirmedDescription: "",
    },
  };
  
  export const getConfirmCardConfig = (type) =>
    confirmCardConfig[type] || confirmCardConfig.default;
  